name: CI for Local Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout il codice
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build e avvio dei servizi
      - name: Build and start services
        run: |
          docker-compose up -d --build
          docker-compose ps

      # Step 4: Testare i servizi
      - name: Run tests
        run: |
          docker-compose run --rm proxy curl -f http://proxy-app:80
          docker-compose run --rm backend curl -f http://backend-app:9000/health
          docker-compose run --rm frontend curl -f http://frontend-app:3000
      # Step 5: Pulizia dei container
      - name: Tear down services
        run: docker-compose down